#!/bin/sh

set -ex

apk --no-cache add --virtual build-dependencies \
    build-base \
    libffi-dev \
    libressl-dev

apk --no-cache add git openssh-client

pip install --no-cache-dir \
    "ansible==${ANSIBLE_VERSION}" \
    "ansible-lint==${ANSIBLELINT_VERSION}" \
    "ruamel.yaml==${RUAMELYAML_VERSION}" \
    "botocore==${BOTOCORE_VERSION}" \
    "boto3==${BOTO3_VERSION}"

apk --no-cache del build-dependencies

touch /etc/login.defs
chmod 0444 /etc/login.defs

chmod 0600 /etc/shadow
